module.exports = function(){
    var content = [
        '',
        '',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHxtttttttt3xHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHhloooooot:)MHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHHHx!HHHHHHHHHHHHHHHHHH',
        'HHHHNFqpppppFMHHHU!HHHHHHHHHHHHHHHHHH',
        'HHHHq,      .RHHHU(HHHHHHHHHHHHHHHHHH',
        'HHHHM)YqppqP`pHHHU(HHHHHHHHHHHHHHHHHH',
        'HHHHH!fHHHHm`pHHHU!HHHHHHHHHHHHHHHHHH',
        'HHHHH!UHHHHF qHHHV!HHHHHHHHHHHHHHHHHH',
        'HHHHH!THHHHq`pHHHU!HHHHHHHHHHHHHHHHHH',
        'HHHHW*`(!!!!.!!!)-?MHHHHHHHHHHHHHHHHH',
        'HHHHHwVUTTUs`sUTTUXHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHQ KHy1cQHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHq pHU  XHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHq pHyCuK0DHRjpl9HHHHwyHHHH',
        'HHHHHHHHHHHq pHH48H-SHX`9 )NHHZ 3HHHH',
        'HHHHHHHHHHHq pHHjjH!UHq.G! SHB) 2HHHH',
        'HHHHHOYHHHHQ`pHHttH(fHR[6"z,A3;lvHHHH',
        'HHHHHt"hfffa qHHotH!YqP.6,d::`FzoHHHH',
        'HHHHHn      -qHHvtHJ   !Z]Kg 4HtoHHHH',
        'HHHHHQFqFFFqpWHHmmMBpqpREpEMpMHKRHHHH',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',

        '              v 0.0.1' ,
        ''
    ].join('\n');
    return content;
};